version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - StratonPro

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - StratonPro
